services:
  - type: web
    name: kra-automations
    env: docker
    dockerfilePath: ./automations/Dockerfile
    dockerContext: ./automations
    plan: standard
    branch: main
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: MAX_CONCURRENT_WORKERS
        value: 3
    healthCheckPath: /health