version: '3.8'
services:
  automation-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - downloads:/app/downloads
    restart: unless-stopped

volumes:
  downloads:
